name: Flutter Build APK

on:
  push:
    branches:
      - main   # Branche que tu veux surveiller
  pull_request:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Installer Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0' # ou la version Flutter que tu utilises

    # 3️⃣ Activer Android SDK
    - name: Accept Android licenses
      run: yes | sdkmanager --licenses

    # 4️⃣ Installer les dépendances Flutter
    - name: Flutter pub get
      run: flutter pub get

    # 5️⃣ Build APK debug
    - name: Build APK Debug
      run: flutter build apk --debug

    # 6️⃣ Upload APK
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: flutter-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
